### ISSUE TITLE
Дополнить  вариативность температуры.

### ISSUE THREAD

**Issue by nikitaCodeSave** [EvilFreelancer/llama-o1-preview#1]
В cot_response = client.chat(model=cot_model, messages=cot_messages)
предлагаю добавить :

,options={"temperature":0.5}

Итого 
cot_response = client.chat(model=cot_model, messages=cot_messages, options={"temperature":0.5})

На генерацию различных гипотез температура играет в плюс, по крайней мере на простых задачах (9.9 или 9.11)

Так как маленькая моделька с температурой 0.0 даже при попытке предложить два варианта (9.9>9.11, 9.9<9.11) в выводах повторяется, а при изменении температуры гипотезы получаются более самостоятельные.

basic_response = client.chat(model=basic_model, messages=basic_messages)
По итогу мне хочется температуру выкрутить в 0.0 но тут у меня нет каких-то предположений.

**Comment by EvilFreelancer** [comment]
Привет! Благодарю за комментарий, внёс предложенные правки в код проекта.

Помимо этого обновил промты, с учётом обсуждений в чате за последние дни.
